"""empty message

Revision ID: 2e9707ace7ca
Revises: 
Create Date: 2022-05-25 20:01:42.838570

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2e9707ace7ca'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'recipes', ['id'])
    op.add_column('test', sa.Column('test_name', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('test', 'test_name')
    op.drop_constraint(None, 'recipes', type_='unique')
    # ### end Alembic commands ###
