"""empty message

Revision ID: 64749e670340
Revises: 2e9707ace7ca
Create Date: 2022-05-25 20:20:55.786589

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '64749e670340'
down_revision = '2e9707ace7ca'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('recipes', sa.Column('likes', sa.Integer(), nullable=True))
    op.add_column('recipes', sa.Column('health_score', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('recipes', 'health_score')
    op.drop_column('recipes', 'likes')
    # ### end Alembic commands ###
